version: "3.3"
services:
  scrapy:
    ports:
      - 9081:9080
    build:
      context: ./scrapy/
      dockerfile: ../.docker/scrapy/Dockerfile
    volumes:
      - ./scrapy:/code

  node:
    image: node:12
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./static:/home/node/app
    command: "yarn"

  web:
    build:
      context: ./
      dockerfile: .docker/flask/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/code

  mongo:
    image: mongo
    restart: always
    ports:
      - 8049:27017
    volumes:
      - ./data/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: covid_ontario
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8061:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  mongodb:
  mongodb_config:
